name: Lint and Test

on:
    push:
        branches:
            - main
    pull_request:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    lint-php:
        name: PHP Lints
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
                  coverage: none
                  tools: composer, cs2pr

            - name: Install PHP dependencies
              uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565
              with:
                  composer-options: '--prefer-dist --no-scripts'

            - name: Validate composer.json
              run: composer validate --no-check-all --strict

            - name: Lint PHP
              run: composer lint
